In [2]:
import numpy as np
#creating array
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)


#array operations
print(arr1 * 2)
print(arr1+arr1)

#reshaping
arr3=np.arange(12).reshape(3,4)
print(arr3)

#matix operation
matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
print(np.dot(matrix1,matrix2))

#statistical operations
data=np.random.normal(0,1,1000)
print(f"Mean:{data.mean()},std:{data.std()}")



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[ 2  4  6  8 10]
[ 2  4  6  8 10]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[19 22]
 [43 50]]
Mean:0.00043945512736827917,std:1.0154614412734944


In [ ]:
import pandas as pd
import numpy as np

# Creating dataFrames
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Salary': [50000, 60000, 70000, 80000]
}
df = pd.DataFrame(data)
print(df)

# Reading from CSV (commented out)
# df = pd.read_csv('data.csv')

# Basic operations
print(df.head(2))  # First 2 rows
print(df.describe())  # Summary statistics
print(df['Age'].mean())  # Average age

# Data Selection
print(df[df['Age'] > 30])  # Filtering
print(df.loc[1:2, ['Name', 'Salary']])  # Selection by label

# Handling missing data
df_with_nan = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8]
})
print(df_with_nan.fillna(value=0))  # Replace NaN with 0
print(df_with_nan.dropna())  # Drop rows with NaN

# Grouping and aggregation
df['Department'] = ['HR', 'Tech', 'Tech', 'HR']
# Fix: Explicitly select numeric columns for aggregation
print(df.groupby('Department')[['Age', 'Salary']].mean())  # Average by department

# Merging DataFrames (like SQL joins)
df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Eve'],
    'Bonus': [2000, 1500, 3000]
})
print(pd.merge(df, df2, on='Name', how='left'))  # Left join

# Time series functionality
date_rng = pd.date_range(start='1/1/2023', end='1/10/2023', freq='D')
ts = pd.DataFrame(date_rng, columns=['date'])
ts['value'] = np.random.randint(0, 100, size=(len(date_rng)))
ts.set_index('date', inplace=True)
print(ts.resample('3D').mean())  # Resample to 3-day periods